graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

spring:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb # in-memory database
    #url: jdbc:h2:file:/Users/gaetan/Work/NCIT/s-echange-nc/data/h2database # file database
    driverClassName: org.h2.Driver
    username: sa
    password: password